apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: crisscoin
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: crisscoin
  minReplicas: 5
  maxReplicas: 10
  targetCPUUtilizationPercentage: 90
